feat(package): add support for custom formats
Workiva/json_schema pull request #135
Opened 2022-03-02 20:43 UTC by michaelcarter-wf

## Ultimate problem:
- We only partially support custom formats (redefining validation for existing formats)

## How it was fixed:
- Allow custom formats in a similar way we expose custom vocabularies
- Deprecate `DefaultValidators` and the global getter / setter.
- Dogfood the basic API for our own format validators.
- Break out into 1-format-validator-per-file

## Testing suggestions:

## Potential areas of regression:

---

> __FYA:__ @michaelcarter-wf

2022-03-02 20:44 UTC, aviary2-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2022-03-02 23:37 UTC, tomdeering-wf commented on example/custom_format/custom_format_example.dart
> +    context.addError('"screaming-caps" format not accepted $instanceData');
LOL :1st_place_medal: for this example

2022-03-02 23:39 UTC, tomdeering-wf commented on lib/src/json_schema/formats/hostname_validator.dart
> +      : JsonSchemaValidationRegexes.hostnameDraft2019;
Are these flipped?

2022-03-02 23:42 UTC, tomdeering-wf commented on lib/src/json_schema/formats/hostname_validator.dart
> +  final regexp = context.schemaVersion > SchemaVersion.draft2019_09
```suggestion
  final regexp = context.schemaVersion < SchemaVersion.draft2019_09
```

2022-03-02 23:46 UTC, tomdeering-wf commented on lib/src/json_schema/validator.dart
> +    final validator = schema.customFormats[schema.format] ?? defaultFormatValidators[schema.format];
The robbie pattern + defaults! I like it!

2022-03-02 23:47 UTC, tomdeering-wf requested changes
Otherwise looks great

2022-03-03 15:48 UTC, michaelcarter-wf commented
+10 

- [x] CI Passes
- [x] Tests added to cover custom formats

2022-03-03 15:48 UTC, michaelcarter-wf commented
@Workiva/release-management-p

2022-03-03 15:49 UTC, rmconsole-wf approved these changes
+1 from RM

2022-03-03 15:49 UTC, merged