V3 README Update
Workiva/json_schema pull request #78
Opened 2021-04-19 18:31 UTC by jordanross-wf

## Ultimate problem:
- Needed to update our readme's for new v3 changes

## How it was fixed:
- Update MIGRATION.md
- Update README.md
- Update the comment on the public `refMap` getter.

## Testing suggestions:
N/A

## Potential areas of regression:
N/A

---

> __FYA:__ @michaelcarter-wf

2021-04-19 18:33 UTC, aviary-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2021-04-19 18:34 UTC, semveraudit-wf commented
### Public API Changes

 No changes to the public API found for commit 6f579781517c0f6662bf46668d44fade180f358b

Showing results for 6f579781517c0f6662bf46668d44fade180f358b
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.1
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/6f579781517c0f6662bf46668d44fade180f358b).

2021-04-21 12:31 UTC, michaelcarter-wf approved these changes
+1

2021-04-21 12:33 UTC, michaelcarter-wf requested changes

2021-04-21 12:33 UTC, michaelcarter-wf commented on MIGRATION.md
> +- Draft 7 is now supported!
Draft 7 is now also the default if you don't specify, so that's another breaking behavioral change

2021-05-17 19:09 UTC, michaelcarter-wf submitted a review, later dismissed
+1

2021-05-17 19:09 UTC, michaelcarter-wf commented
@Workiva/release-management-p

2021-05-17 19:15 UTC, michaelcarter-wf approved these changes
+1

2021-05-17 19:20 UTC, michaelcarter-wf commented
@Workiva/release-management-p

2021-05-17 19:26 UTC, michaelcarter-wf commented
@Workiva/release-management-p

2021-05-17 19:36 UTC, michaelcarter-wf commented
@Workiva/release-management-p

2021-05-17 19:37 UTC, rmconsole-wf approved these changes
+1 from RM

2021-05-17 19:37 UTC, merged